server:
  port: 8888
idp:
  url: http://localhost:8180
  client-id: gateway-id
  client-secret: ENCQbCyZKjMLlyqZ3crfx4i933Pw6a0i
app:
  api-prefix: /api/v1
spring:
  security:
    oauth2:
      resourceserver:
        issuer-uri: http://localhost:8180/realms/hoagShop
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: profile_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: order_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
